### ISSUE TITLE
Non-zero return code on error

### ISSUE THREAD

**Issue by jhmartin** [cdoughty77/knife-syntax-check#1]
This would make a nice component of a Travis-CI/Drone.IO test for a chef configuration. Please consider having it return a non-0 exit code if it finds any syntax errors.

For example:

```
name "admin"
Finding type environment to test from environments/*
Testing file environments/admin.rb
environments/admin.rb:24: `@#' is not allowed as an instance variable name
```

Yet the return code was 0. I see that it does abort nicely when there is a JSON failure though.

**Comment by cdoughty77** [comment]
Should be resolved with  987a5273da4080424c6f0a1e1ba2313c48c7ad45 but let me know if you see further issues.  Glad you find the script useful and thanks for the feedback!
